# Generated by Django 5.2.4 on 2025-07-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tag_task_category_name_checklistitem_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
